#ifndef __DDRCOMMLIB_MARS_LOCALSERVICEMODULE_COMMON_CONFIG_H_INCLUDED__
#define __DDRCOMMLIB_MARS_LOCALSERVICEMODULE_COMMON_CONFIG_H_INCLUDED__

#include <vector>
//#include <WinSock2.h>

namespace DDRCommLib { namespace MARS {

const int RECONNECTION_PERIOD = 5000;
const int CONNECTION_TIMEOUT = 5000;
const int LOGINGIN_TIMEOUT = 5000;
const int HB_SENDING_PERIOD = 5000;
const int MAX_TIME_FOR_INACTIVE_CONNECTION = 15000;
const int CALLING_REQ_ACK_PERIOD = 50;
const int CALLING_MAX_INACTIVE_TIME = 10000; // xcy add
const int CALLING_MAX_RINGING_TIME = 30000;

const char DDRLNB_NODEINFO_BROADCASTING_ADDRESS_IP[] = "239.0.0.127";
const unsigned short DDRLNB_NODEINFO_BROADCASTING_ADDRESS_PORT = 28888;

//bool _receive(SOCKET s, std::vector<char> &vec);

}}

#endif // __DDRCOMMLIB_MARS_LOCALSERVICEMODULE_COMMON_CONFIG_H_INCLUDED__

